// <auto-generated />
namespace QLTHUVIEN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class QLTVv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QLTVv1));
        
        string IMigrationMetadata.Id
        {
            get { return "202504250357028_QLTV-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
